name: Michael Cato
favicon: null
layout_spectrum: 0.3118843729607761
typography_spectrum: 0.28724491968750954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8687605287414044
  lightness: 0.8065816781017929
  saturation: 0.8690106684807688
  rhythmicContrast: 0.3513240432366729
purpose: []
